name: CI

on: [push]

permissions:
  contents: read

jobs:
  workspace-ci:
    name: Workspace CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]

    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - uses: ./.github/reusable-workflows/setup-repo
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check for a changelog entry
        if: ${{ github.ref != 'refs/heads/prepare-release' && github.actor != 'dependabot[bot]' }}
        run: |
          pnpm run changelog:status:ci

      - name: Run CI checks
        run: |
          pnpm run all:ci

      - name: Report test coverage to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ github.token }}

  package-ci:
    name: Package CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-name: [tiny-immutable-set]

    steps:
      - uses: actions/checkout@v3.5.3

      - uses: ./.github/reusable-workflows/setup-repo
        with:
          node-version: latest

      - name: Run CI checks for package
        run: |
          cd packages/${{ matrix.package-name }}
          pnpm run all:ci
